### ISSUE TITLE
General Feature Requests

### ISSUE THREAD

**Issue by WilliamConnatser** [runcitadel/ui#1]
What features would ya'll like to see Citadel have?

I'll get us started!

As a user, I want to...
 - Enable two factor authentication while logging in to my Citadel
 - Configure 2fa via the UI in a section on the "Settings View"
 - Add, remove, or edit many different authentication methods
 - Configure my 2fa settings with many combinations of M of N access control
 - Be able to use several hardware authentication devices (YubiKey, etc)

**Comment by AaronDewes** [comment]
I''m working on the backend for 2FA currently.

> Be able to use several hardware authentication devices (YubiKey, etc)

The problem with that is that this only works over HTTPS, which we can't add easily. It works over Tor though, so maybe a Tor login only mode?

**Comment by WilliamConnatser** [comment]
"The problem with that is that this only works over HTTPS"

That is a good point that I had not considered. I have never used these APIs before, but it does indeed look like both the USB and the new NFC API require HTTPS. I also agree it will not be easy to add HTTPS, but I think we should make implementing that a priority because we need to move key management to hardware wallets too.

I realize they are not small problems to solve, but I think they are solvable in time. I have confidence we can figure it out though, and would like to suggest that implementing HTTPS, 2fa, and USB/NFC support be a priority.

It looks like we will need to generate the certificates to become our on CA on the Citadel, and somehow get them to the devices we will be using it with and configure it differently depending on the OS of the device. We can't transfer the certificates over HTTP because of MIM attacks so we need to treat our Citadel as a secure environment.
- HTTPS setup would be added as the first step of set up before key generation.
- We need to be able to select the type of device (and/or OS) on the UI, and validate the options user chose on our Citadel after the device is plugged in.
- The Citadel will be in "listen mode" listening for new USB devices being plugged into our Citadel.
   - We can integrate support for NFC USB interfaces later.
- We need to write a tool for each OS to get that certificate where it needs to be.
- Once the certificates are shared among devices HTTPS will work.

I agree a TOR-only solution would be easier, and perhaps we can start with that? However, IMO HTTPS is necessary for security purposes. IMO increased security should be a priority, and come before almost all other additional features (except for the really easy ones, of course).

Is this something like this what you had in mind Aaron? I am wondering if there may be a better way... this is just the first solution that popped in my head. Let me know what ya'll think about this. :)

**Comment by AaronDewes** [comment]
Yes, I was thinking about something similar. I'm building a custom Citadel OS flashing tool, which could generate and install the certificate locally on the computer used to flash, and a custom tool (or at least a guide) to only install the certificate should be possible too.

**Comment by AaronDewes** [comment]
Another feature I'd like is translations for the dashboard. If you'll use a date library for something, I know `date-fns` has translations.
Also, when adding translations, please keep date format strings to translate too, different languages have different date standards.

I can help with German translation and I know someone who is willing to help with Spanish translations.

**Comment by WilliamConnatser** [comment]
Sounds good! I have been thinking about doing something along those lines too. I added "react-aria" hooks to the base components to increase the application's accessibility in general, and it seems like we could use the "react-intl" package to handle different languages. That is the package the react-aria docs suggest, anyways. I will research how best to implement this because all of the applications I have built have been in English. Thanks for bringing this up.. it should be built in from the beginning to save a lot of re-work. :+1:

**Comment by WilliamConnatser** [comment]
When I set up this GitHub Issue, we did not have any alternative communication methods set up, but that has changed and a lot of this information is out of date based on developer communications off GitHub so we've decided to close this issue.

Please contact us on Twitter (@ runcitadel) or on Telegram (https://t.me/runcitadel) if you have any ideas, feedback or if you would like to help us design and/or develop Citadel. Thanks!
